#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='dbg.dc+ds.swstep'
FILE=../../bins/elf/analysis/elf-nx
ARGS=-d
BROKEN=
CMDS='e scr.color=0
db entry0
dc
dr PC
'
EXPECT='
'
run_test
