#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='dbg.dcC+ds.swstep1'
FILE=/bin/ls
ARGS=-d
BROKEN=
CMDS='e scr.color=0
e dbg.swstep=true
dr PC
dc
dr PC
'
EXPECT='
'
run_test
